<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TaskDescription [
	<!ELEMENT TaskDescription (State+)>

	<!ELEMENT State ((ROBOT|SetOfRobots)?,ECPGeneratorType?,TrajectoryFilePath?,Trajectory?,taskInit?,
							Speech?,AddArg?,Sensor?,TimeSpan?,GeneratorParameters?,transition+)>
		<!ATTLIST State id CDATA #REQUIRED>
		<!ATTLIST State type CDATA #REQUIRED>

	<!ELEMENT SetOfRobots (FirstSet?, SecSet?)>
	
	<!ELEMENT FirstSet (ROBOT+)>
	<!ELEMENT SecSet (ROBOT+)>

	<!ELEMENT ROBOT (#PCDATA)>
	<!ELEMENT ECPGeneratorType (#PCDATA)>
	<!ELEMENT TrajectoryFilePath (#PCDATA)>
	<!ELEMENT Trajectory (Pose+)>
		<!ATTLIST Trajectory coordinateType CDATA #REQUIRED>
		<!ATTLIST Trajectory numOfPoses CDATA #REQUIRED>
		
	<!ELEMENT Pose (StartVelocity,EndVelocity,Velocity,Accelerations,Coordinates)>
		<!ELEMENT StartVelocity (#PCDATA)>
		<!ELEMENT EndVelocity (#PCDATA)>
		<!ELEMENT Velocity (#PCDATA)>
		<!ELEMENT Accelerations (#PCDATA)>
		<!ELEMENT Coordinates (#PCDATA)>
	
	<!ELEMENT taskInit (ecp+,mp?)>
	<!ELEMENT ecp (ecp_gen_t?,ecp_tool_change_gen?,ecp_tff_nose_run_gen?,ecp_tff_rubik_grab_gen?,
		ecp_tff_gripper_approach_gen?,ecp_tff_rubik_face_rotate_gen?,ecp_teach_in_gen?,
		bias_edp_force_gen?,ecp_smooth_gen?,weight_meassure_gen?,ecp_sub_task_gripper_opening?)>
		<!ATTLIST ecp name CDATA #REQUIRED>
		<!ELEMENT ecp_gen_t (#PCDATA)>
		<!ELEMENT ecp_tool_change_gen (#PCDATA)>
		<!ELEMENT ecp_tff_nose_run_gen (#PCDATA)>
		<!ELEMENT ecp_tff_rubik_grab_gen (#PCDATA)>
		<!ELEMENT ecp_tff_gripper_approach_gen (#PCDATA)>
		<!ELEMENT ecp_tff_rubik_face_rotate_gen (#PCDATA)>
		<!ELEMENT ecp_teach_in_gen (#PCDATA)>
		<!ELEMENT bias_edp_force_gen (#PCDATA)>
		<!ELEMENT ecp_smooth_gen (#PCDATA)>
		<!ELEMENT weight_meassure_gen (#PCDATA)>
		<!ELEMENT ecp_sub_task_gripper_opening (#PCDATA)>
	
	<!ELEMENT mp (#PCDATA)>
	
	<!ELEMENT Speech (#PCDATA)>
	<!ELEMENT AddArg (#PCDATA)>
	<!ELEMENT Sensor (#PCDATA)>
	<!ELEMENT TimeSpan (#PCDATA)>
	<!ELEMENT GeneratorParameters (#PCDATA)>

	<!ELEMENT transition (#PCDATA)>
		<!ATTLIST transition condition CDATA #REQUIRED>
		<!ATTLIST transition target CDATA #REQUIRED>
]>
<!--	
	Autor: Marek Kisiel
	Data: 2008
	Zadanie nalewania: "pouring"
-->
<TaskDescription>
	<State id="INIT" type="systemInitialization">
		<taskInit>
			<ecp name="ROBOT_IRP6_ON_TRACK">
				<ecp_tool_change_gen>1</ecp_tool_change_gen>
				<ecp_smooth_gen>1</ecp_smooth_gen>
				<ecp_sub_task_gripper_opening></ecp_sub_task_gripper_opening>		
			</ecp>
			<ecp name="ROBOT_IRP6_POSTUMENT">
				<ecp_smooth_gen>1</ecp_smooth_gen>
				<ecp_sub_task_gripper_opening></ecp_sub_task_gripper_opening>		
			</ecp>
		</taskInit>	
		<transition condition="true" target="approach_1"/>
	</State>
	<State id="approach_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_ap.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	0.05</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.1</Accelerations>
				<Coordinates>0	0.1	-1.162	0.172	1.367	2.936	1.371	0.088</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="approach_2"/>
	</State>
	<State id="approach_2" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_p_ap.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.04	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.1</Accelerations>
				<Coordinates>-0.072647	-1.50328	0.162187	1.49219	2.33216	-1.62241	0.08	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="approach_end"/>
	</State>
	<State id="approach_end" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="grab_1"/>
	</State>
	<State id="grab_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_grab.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.01	0.01	0.01	0.01	0.01	0.01	1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.948	-0.309	0.145	-1.269	1.529	0	0.088	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="grab_2"/>
	</State>
	<State id="grab_2" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_p_grab.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.01	0.01	0.01	0.01	0.01	0.01	0.1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	1</Accelerations>
				<Coordinates>0.84	1.774	0.083	-0.868	1.504	-3.128	0.088	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="grab_end_1"/>
	</State>
	<State id="grab_end_1" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="grab_3"/>
	</State>
	<State id="grab_3" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>RCSC_GRIPPER_OPENING</ECPGeneratorType>
		<GeneratorParameters>-0.03	1000</GeneratorParameters>
		<transition condition="true" target="grab_4"/>
	</State>
	<State id="grab_4" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>RCSC_GRIPPER_OPENING</ECPGeneratorType>
		<GeneratorParameters>-0.018	1000</GeneratorParameters>
		<transition condition="true" target="grab_end_2"/>
	</State>
	<State id="grab_end_2" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="weight_1"/>
	</State>
	<State id="weight_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_weight.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.948	-0.309	0.185	-1.269	1.529	0	0.058	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="weight_2"/>
	</State>
	<State id="weight_2" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_p_weight.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.01	0.01	0.01	0.01	0.01	0.01	0.1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	1</Accelerations>
				<Coordinates>0.84	1.774	0.123	-0.868	1.504	-3.128	0.088	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="weight_end"/>
	</State>
	<State id="weight_end" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="meet_1"/>
	</State>
	<State id="meet_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_meet.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="3">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.777	-0.031	0.185	-0.031	1.529	0	0.058	0</Coordinates>
			</Pose>
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.607	0.262	0.185	-0.031	1.529	0	0.058	0</Coordinates>
			</Pose>
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.05	0.05	0.05	0.05	0.05	0.05	1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.507	0.762	0.185	-0.031	1.529	0	0.058	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="meet_2"/>
	</State>
	<State id="meet_2" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_p_meet.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.05	0.05	0.05	0.05	0.05	0.05	1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.274	1.024	0.141	-0.868	1.504	-3.128	0.068	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="meet_end_1"/>
	</State>
	<State id="meet_end_1" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="meet_3"/>
	</State>
	<State id="meet_3" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_track_meet.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.05	0.1	0.1	0.1	0.1	0.1	1	1</Velocity>
				<Accelerations>0.05	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.16	1.24794	-1.30501	0.111729	1.42472	2.84922	1.43126	0.058</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="meet_end_2"/>
	</State>
	<State id="meet_end_2" type="emptyGen">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>		
		<AddArg>0</AddArg>
		<transition condition="true" target="pour_1"/>
	</State>
	<State id="pour_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_TOOL_CHANGE_GENERATOR</ECPGeneratorType>
		<GeneratorParameters>-0.18	0.0	0.25</GeneratorParameters>
		<transition condition="true" target="pour_end_1"/>
	</State>
	<State id="pour_end_1" type="emptyGen">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<AddArg>0</AddArg>
		<transition condition="true" target="pour_2"/>
	</State>
	<State id="pour_2" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_pour_2.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.01	0.01	0.01	0.01	0.01	0.01	0.1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.51	1.088	0.255	-0.034	1.528	-2	0.058	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="pour_end_2"/>
	</State>
	<State id="pour_end_2" type="emptyGen">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<AddArg>0</AddArg>
		<transition condition="true" target="pour_3"/>
	</State>
	<State id="pour_3" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_pour_3.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.05	0.05	0.05	0.05	0.05	0.05	0.1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.51	1.088	0.255	-0.034	1.528	-1.18	0.058	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="pour_end_3"/>
	</State>
	<State id="pour_end_3" type="emptyGen">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<AddArg>0</AddArg>
		<transition condition="true" target="pour_4"/>
	</State>
	<State id="pour_4" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_TOOL_CHANGE_GENERATOR</ECPGeneratorType>
		<GeneratorParameters>0.0	0.0	0.25</GeneratorParameters>
		<transition condition="true" target="pour_end_4"/>
	</State>
	<State id="pour_end_4" type="emptyGen">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<AddArg>0</AddArg>
		<transition condition="true" target="pour_5"/>
	</State>
	<State id="pour_5" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_pour_4.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.507	0.922	0.186	-0.033	1.528	0	0.058	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="pour_end_5"/>
	</State>
	<State id="pour_end_5" type="emptyGen">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<AddArg>0</AddArg>
		<transition condition="true" target="go_back_1"/>
	</State>
	<State id="go_back_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_track_put_back.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.05	0.1	0.1	0.1	0.1	0.1	1	1</Velocity>
				<Accelerations>0.05	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0	1.24794	-1.30501	0.111729	1.42472	2.84922	1.43126	0.058</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="go_back_end_1"/>
	</State>
	<State id="go_back_end_1" type="emptyGen">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>		
		<AddArg>0</AddArg>
		<transition condition="true" target="go_back_2"/>
	</State>
	<State id="go_back_2" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_go_back.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="3">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.607	0.262	0.185	-0.031	1.529	0	0.058	0</Coordinates>
			</Pose>
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.05	0.05	0.05	0.05	0.05	0.05	1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.777	-0.031	0.185	-0.031	1.529	0	0.058	0</Coordinates>
			</Pose>
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.948	-0.309	0.185	-1.269	1.529	0	0.058	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="go_back_3"/>
	</State>
	<State id="go_back_3" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_p_go_back.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.1	0.1	0.1	0.1	0.1	0.1	0.1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	1</Accelerations>   
				<Coordinates>0.84	1.774	0.123	-0.868	1.504	-3.128	0.068	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="go_back_end_2"/>
	</State>
	<State id="go_back_end_2" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="put_back_1"/>
	</State>
	<State id="put_back_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_put_back.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.01	0.01	0.01	0.01	0.01	0.01	1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	1	1</Accelerations>
				<Coordinates>0.948	-0.309	0.145	-1.269	1.529	0	0.058	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="put_back_2"/>
	</State>
	<State id="put_back_2" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_p_put_back.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.01	0.01	0.01	0.01	0.01	0.01	0.1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	1</Accelerations>
				<Coordinates>0.84	1.774	0.083	-0.868	1.504	-3.128	0.068	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="put_back_end_1"/>
	</State>
	<State id="put_back_end_1" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="put_back_3"/>
	</State>
	<State id="put_back_3" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>RCSC_GRIPPER_OPENING</ECPGeneratorType>
		<GeneratorParameters>0.03	1000</GeneratorParameters>
		<transition condition="true" target="put_back_4"/>
	</State>
	<State id="put_back_4" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>RCSC_GRIPPER_OPENING</ECPGeneratorType>
		<GeneratorParameters>0.015	1000</GeneratorParameters>
		<transition condition="true" target="put_back_end_2"/>
	</State>
	<State id="put_back_end_2" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="put_back_5"/>
	</State>
	<State id="put_back_5" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_dep_1.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.01	0.01	0.01	0.1	0.01	0.01	0.1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.1</Accelerations>
				<Coordinates>0.948	-0.161	0.145	-1.269	1.529	0	0.088	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="put_back_6"/>
	</State>
	<State id="put_back_6" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_p_dep_1.trj</TrajectoryFilePath>
		<Trajectory coordinateType="XYZ_EULER_ZYZ" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.01	0.01	0.01	0.01	0.01	0.01	0.1	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.1</Accelerations>
				<Coordinates>0.789	1.842	0.152	-0.868	1.504	-3.128	0.088	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="put_back_end_3"/>
	</State>
	<State id="put_back_end_3" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="depart_1"/>
	</State>
	<State id="depart_1" type="runGenerator">
		<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_ot_dep_2.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>0	-0.087404	-1.54182	0.024063	1.21873	2.59131	-2.66439	0.073999</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="depart_2"/>
	</State>
	<State id="depart_2" type="runGenerator">
		<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>
		<ECPGeneratorType>ECP_GEN_SMOOTH</ECPGeneratorType>
		<TrajectoryFilePath>trj/pouring/irp6_p_dep_2.trj</TrajectoryFilePath>
		<Trajectory coordinateType="JOINT" numOfPoses="1">
			<Pose>
				<StartVelocity>0	0	0	0	0	0	0	0</StartVelocity>
				<EndVelocity>0	0	0	0	0	0	0	0</EndVelocity>
				<Velocity>0.5	0.5	0.5	0.5	0.5	0.5	0.5	1</Velocity>
				<Accelerations>0.1	0.1	0.1	0.1	0.1	0.1	0.1	0.01</Accelerations>
				<Coordinates>-0.100623	-1.54194	0.048609	1.19772	2.10098	-2.73118	0.088	0</Coordinates>
			</Pose>
		</Trajectory>
		<transition condition="true" target="depart_end"/>
	</State>
	<State id="depart_end" type="emptyGenForSet">
		<SetOfRobots>
			<FirstSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</FirstSet>			
			<SecSet>
				<ROBOT>ROBOT_IRP6_ON_TRACK</ROBOT>
				<ROBOT>ROBOT_IRP6_POSTUMENT</ROBOT>		
			</SecSet>
		</SetOfRobots>
		<transition condition="true" target="STOP"></transition>
	</State>
</TaskDescription>
